### ISSUE TITLE
"No such file or directory" on compile

### ISSUE THREAD

**Issue by Juggernaut1994** [jagannatharjun/qbt-theme#8]
What command I used: 
`make-resource.py -o mytheme.qbttheme -s stylesheet.qrc`

What I've got:
```
Traceback (most recent call last):
  File "C:\reallydarkstylesheet\make-resource.py", line 45, in <module>
    subprocess.call(['rcc', '-binary', '-o', args.output, '--root', '/', 'resources.qrc'])
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] No such file or directory
```

**Comment by jagannatharjun** [comment]
rcc is now directly included in rep
